"""Hand-computed golden tests for the brute-force window oracle.

Every expected row in this module was computed by hand from the literal
source candles above it and written out here as a literal. None of it is
generated by the oracle: these tests are the specification, and a
generated expectation would only prove the oracle agrees with itself.

The inclusion rule under test, restated: at emit time ``t``, a finalized
source candle spanning ``[open_time, close_time)`` belongs to the window
of duration ``W`` if and only if ``open_time >= t - W`` and
``close_time <= t``. Candles are never split at a boundary.
"""

import polars as pl
import pytest
from ohlc_toolkit.windows import (
    ExplicitRange,
    MaterializationRule,
    compute_reference_windows,
)
from polars.testing import assert_frame_equal

from tests.test_windows.factories import (
    SourceRow,
    expected_frame,
    frame_from_rows,
    profile_for,
)

# Six one-minute candles on a clean 60s grid, opening at 0 and closing at
# 360. Volumes are distinct powers of two so that any wrong subset sums to
# a recognisably wrong total.
_SIX_MINUTE_CANDLES: tuple[SourceRow, ...] = (
    (0, 100.0, 110.0, 90.0, 105.0, 1.0),
    (60, 101.0, 111.0, 91.0, 106.0, 2.0),
    (120, 102.0, 112.0, 92.0, 107.0, 4.0),
    (180, 103.0, 113.0, 93.0, 108.0, 8.0),
    (240, 104.0, 114.0, 94.0, 109.0, 16.0),
    (300, 105.0, 115.0, 95.0, 110.0, 32.0),
)

# Five one-second candles, opening at 0 and closing at 5.
_FIVE_SECOND_CANDLES: tuple[SourceRow, ...] = (
    (0, 10.0, 20.0, 5.0, 15.0, 1.0),
    (1, 11.0, 21.0, 6.0, 16.0, 2.0),
    (2, 12.0, 22.0, 7.0, 17.0, 3.0),
    (3, 13.0, 23.0, 8.0, 18.0, 4.0),
    (4, 14.0, 24.0, 9.0, 19.0, 5.0),
)


def test_aligned_tiling_emits_one_row_per_tile() -> None:
    """W == E tiles the timeline: three source candles per window, no overlap.

    Ticks are 180, 360, and 540. The last tile lies entirely past the data,
    so it still emits a row -- an empty one.
    """
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="3m",
        materialization=ExplicitRange(start=180, end=541),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 180): candles opening at 0, 60, 120.
                (0, 180, 100.0, 112.0, 90.0, 107.0, 7.0, 3, 180),
                # [180, 360): candles opening at 180, 240, 300.
                (180, 360, 103.0, 115.0, 93.0, 110.0, 56.0, 3, 180),
                # [360, 540): no candle opens at or after 360.
                (360, 540, None, None, None, None, None, 0, 0),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_overlapping_windows_emit_every_minute_over_a_three_minute_window() -> None:
    """E < W: consecutive windows share candles, and each is aggregated whole."""
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="1m",
        materialization=ExplicitRange(start=180, end=361),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 180): candles opening at 0, 60, 120.
                (0, 180, 100.0, 112.0, 90.0, 107.0, 7.0, 3, 180),
                # [60, 240): candles opening at 60, 120, 180.
                (60, 240, 101.0, 113.0, 91.0, 108.0, 14.0, 3, 180),
                # [120, 300): candles opening at 120, 180, 240.
                (120, 300, 102.0, 114.0, 92.0, 109.0, 28.0, 3, 180),
                # [180, 360): candles opening at 180, 240, 300.
                (180, 360, 103.0, 115.0, 93.0, 110.0, 56.0, 3, 180),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_nonzero_anchor_shifts_the_emit_grid_off_the_round_boundaries() -> None:
    """An anchor of 1m puts the 3m emit grid on 60, 240, 420 instead of 0, 180.

    The trailing tick is only partly covered: its window reaches past the
    last candle's close, so ``coverage_seconds`` is 60, not the full 120.
    """
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="2m",
        emit_every="3m",
        anchor="1m",
        materialization=ExplicitRange(start=240, end=421),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [120, 240): candles opening at 120 and 180.
                (120, 240, 102.0, 113.0, 92.0, 108.0, 12.0, 2, 120),
                # [300, 420): only the candle opening at 300 exists.
                (300, 420, 105.0, 115.0, 95.0, 110.0, 32.0, 1, 60),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_anchor_is_normalized_modulo_the_emit_cadence() -> None:
    """Anchors 1m and 4m describe the same 3m grid, so they must agree exactly."""
    frame = frame_from_rows(_SIX_MINUTE_CANDLES)
    profile = profile_for(60)
    materialization = ExplicitRange(start=240, end=421)

    one_minute_anchor = compute_reference_windows(
        frame,
        profile,
        window="2m",
        emit_every="3m",
        anchor="1m",
        materialization=materialization,
    )
    four_minute_anchor = compute_reference_windows(
        frame,
        profile,
        window="2m",
        emit_every="3m",
        anchor="4m",
        materialization=materialization,
    )

    assert_frame_equal(one_minute_anchor, four_minute_anchor)


def test_one_second_cadence_aggregates_second_level_candles() -> None:
    """A 1s source with a 3s window and a 1s emit cadence works exactly."""
    result = compute_reference_windows(
        frame_from_rows(_FIVE_SECOND_CANDLES),
        profile_for(1),
        window="3s",
        emit_every="1s",
        materialization=ExplicitRange(start=3, end=6),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 3): candles opening at 0, 1, 2.
                (0, 3, 10.0, 22.0, 5.0, 17.0, 6.0, 3, 3),
                # [1, 4): candles opening at 1, 2, 3.
                (1, 4, 11.0, 23.0, 6.0, 18.0, 9.0, 3, 3),
                # [2, 5): candles opening at 2, 3, 4.
                (2, 5, 12.0, 24.0, 7.0, 19.0, 12.0, 3, 3),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_window_spanning_a_gap_reports_partial_coverage() -> None:
    """A missing source candle lowers coverage_seconds without shifting anything.

    The candle that would have opened at 120 is absent, so the 240s window
    holds three of a possible four candles and covers 180 of 240 seconds.
    """
    rows = (
        _SIX_MINUTE_CANDLES[0],
        _SIX_MINUTE_CANDLES[1],
        _SIX_MINUTE_CANDLES[3],
        _SIX_MINUTE_CANDLES[4],
    )
    result = compute_reference_windows(
        frame_from_rows(rows),
        profile_for(60),
        window="4m",
        emit_every="4m",
        materialization=ExplicitRange(start=240, end=241),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 240): candles opening at 0, 60, and 180; the candle
                # opening at 240 closes at 300, past the window's end.
                (0, 240, 100.0, 113.0, 90.0, 108.0, 11.0, 3, 180),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_candle_closing_exactly_at_the_emit_time_is_included() -> None:
    """A candle whose close_time equals t is fully known at t, so it counts."""
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES[:2]),
        profile_for(60),
        window="1m",
        emit_every="1m",
        materialization=ExplicitRange(start=60, end=61),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 60): the candle opening at 0 closes exactly at t=60.
                (0, 60, 100.0, 110.0, 90.0, 105.0, 1.0, 1, 60),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_candle_straddling_the_window_open_is_excluded_whole() -> None:
    """A candle opening before t - W is dropped entirely, never split.

    The straddling candle spans [30, 90) while the window is [60, 180). Its
    extreme high and low would be unmistakable in the output if any part of
    it leaked in.
    """
    rows: tuple[SourceRow, ...] = (
        (0, 100.0, 110.0, 90.0, 105.0, 1.0),
        (30, 200.0, 300.0, 50.0, 250.0, 64.0),
        (60, 102.0, 112.0, 92.0, 107.0, 4.0),
        (120, 103.0, 113.0, 93.0, 108.0, 8.0),
    )
    result = compute_reference_windows(
        frame_from_rows(rows),
        profile_for(60),
        window="2m",
        emit_every="2m",
        materialization=ExplicitRange(start=180, end=181),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [60, 180): candles opening at 60 and 120 only.
                (60, 180, 102.0, 113.0, 92.0, 108.0, 12.0, 2, 120),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_candle_straddling_the_emit_time_is_excluded_whole() -> None:
    """A candle still open at t is not yet knowable at t, so it is dropped.

    The straddling candle spans [150, 210) while the window is [0, 180).
    Its open_time passes the lower boundary test; only the close_time test
    excludes it, which is why the oracle must always test both.
    """
    rows: tuple[SourceRow, ...] = (
        (0, 100.0, 110.0, 90.0, 105.0, 1.0),
        (60, 101.0, 111.0, 91.0, 106.0, 2.0),
        (150, 999.0, 1999.0, 1.0, 888.0, 128.0),
    )
    result = compute_reference_windows(
        frame_from_rows(rows),
        profile_for(60),
        window="3m",
        emit_every="3m",
        materialization=ExplicitRange(start=180, end=181),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 180): candles opening at 0 and 60 only.
                (0, 180, 100.0, 111.0, 90.0, 106.0, 3.0, 2, 120),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_explicit_range_emits_empty_rows_before_and_after_all_data() -> None:
    """The emit grid is total: every tick in [start, end) emits, data or not."""
    rows: tuple[SourceRow, ...] = (
        (300, 100.0, 110.0, 90.0, 105.0, 1.0),
        (360, 101.0, 111.0, 91.0, 106.0, 2.0),
    )
    result = compute_reference_windows(
        frame_from_rows(rows),
        profile_for(60),
        window="1m",
        emit_every="1m",
        materialization=ExplicitRange(start=60, end=601),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                (0, 60, None, None, None, None, None, 0, 0),
                (60, 120, None, None, None, None, None, 0, 0),
                (120, 180, None, None, None, None, None, 0, 0),
                (180, 240, None, None, None, None, None, 0, 0),
                # [240, 300): the candle opening at 300 closes at 360, so
                # it is not knowable at t=300.
                (240, 300, None, None, None, None, None, 0, 0),
                (300, 360, 100.0, 110.0, 90.0, 105.0, 1.0, 1, 60),
                (360, 420, 101.0, 111.0, 91.0, 106.0, 2.0, 1, 60),
                (420, 480, None, None, None, None, None, 0, 0),
                (480, 540, None, None, None, None, None, 0, 0),
                (540, 600, None, None, None, None, None, 0, 0),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_skip_warmup_starts_at_the_first_fully_covered_tick() -> None:
    """skip_warmup drops the partly-covered lead-in and stops at the last tick.

    The source spans [0, 360). With a 180s window on a 60s emit grid, the
    first fully covered tick is 180 and the last tick at or before the
    final close is 360.
    """
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="1m",
        materialization=MaterializationRule.SKIP_WARMUP,
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                (0, 180, 100.0, 112.0, 90.0, 107.0, 7.0, 3, 180),
                (60, 240, 101.0, 113.0, 91.0, 108.0, 14.0, 3, 180),
                (120, 300, 102.0, 114.0, 92.0, 109.0, 28.0, 3, 180),
                (180, 360, 103.0, 115.0, 93.0, 110.0, 56.0, 3, 180),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_skip_warmup_accepts_a_later_gap_after_the_first_covered_tick() -> None:
    """Full coverage is only required of the FIRST tick, not of every tick.

    The candle that would have opened at 120 is missing, but the window
    ending at 120 is already fully covered, so materialization starts
    there and the later partly-covered ticks are still emitted.
    """
    rows = (
        _SIX_MINUTE_CANDLES[0],
        _SIX_MINUTE_CANDLES[1],
        _SIX_MINUTE_CANDLES[3],
        _SIX_MINUTE_CANDLES[4],
        _SIX_MINUTE_CANDLES[5],
    )
    result = compute_reference_windows(
        frame_from_rows(rows),
        profile_for(60),
        window="2m",
        emit_every="1m",
        materialization=MaterializationRule.SKIP_WARMUP,
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                # [0, 120): candles opening at 0 and 60; fully covered.
                (0, 120, 100.0, 111.0, 90.0, 106.0, 3.0, 2, 120),
                # [60, 180): only the candle opening at 60 survives.
                (60, 180, 101.0, 111.0, 91.0, 106.0, 2.0, 1, 60),
                # [120, 240): only the candle opening at 180.
                (120, 240, 103.0, 113.0, 93.0, 108.0, 8.0, 1, 60),
                # [180, 300): candles opening at 180 and 240.
                (180, 300, 103.0, 114.0, 93.0, 109.0, 24.0, 2, 120),
                # [240, 360): candles opening at 240 and 300.
                (240, 360, 104.0, 115.0, 94.0, 110.0, 48.0, 2, 120),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_skip_warmup_accepts_the_plain_rule_name_as_a_string() -> None:
    """The named rule is accepted as a string at the public boundary."""
    by_string = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="1m",
        materialization="skip_warmup",
    )
    by_enum = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="1m",
        materialization=MaterializationRule.SKIP_WARMUP,
    )

    assert_frame_equal(by_string, by_enum)


def test_output_schema_is_exactly_the_nine_declared_columns() -> None:
    """The output columns, their order, and their dtypes are a fixed contract."""
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="3m",
        materialization=ExplicitRange(start=180, end=361),
    )

    assert result.columns == [
        "open_time",
        "close_time",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "src_count",
        "coverage_seconds",
    ]
    assert result.dtypes == [
        pl.Int64,
        pl.Int64,
        pl.Float64,
        pl.Float64,
        pl.Float64,
        pl.Float64,
        pl.Float64,
        pl.UInt32,
        pl.Int64,
    ]
    # The ambiguous name the output contract deliberately refuses to use.
    assert "timestamp" not in result.columns


def test_empty_tick_range_still_returns_the_declared_schema() -> None:
    """A range containing no grid tick returns zero rows, not a shapeless frame."""
    result = compute_reference_windows(
        frame_from_rows(_SIX_MINUTE_CANDLES),
        profile_for(60),
        window="3m",
        emit_every="3m",
        materialization=ExplicitRange(start=181, end=181),
    )

    assert result.height == 0
    assert result.columns == [
        "open_time",
        "close_time",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "src_count",
        "coverage_seconds",
    ]


def test_an_empty_source_frame_emits_every_tick_as_an_empty_window() -> None:
    """Zero source rows is not zero output rows: the grid is still total."""
    result = compute_reference_windows(
        frame_from_rows(()),
        profile_for(60),
        window="1m",
        emit_every="1m",
        materialization=ExplicitRange(start=60, end=181),
    )

    assert_frame_equal(
        result,
        expected_frame(
            [
                (0, 60, None, None, None, None, None, 0, 0),
                (60, 120, None, None, None, None, None, 0, 0),
                (120, 180, None, None, None, None, None, 0, 0),
            ]
        ),
        check_dtypes=True,
        check_column_order=True,
        check_row_order=True,
    )


def test_the_input_frame_is_never_mutated() -> None:
    """The oracle reads its input and nothing else: no sort, no repair, no edit."""
    frame = frame_from_rows(_SIX_MINUTE_CANDLES)
    before = frame.clone()

    compute_reference_windows(
        frame,
        profile_for(60),
        window="3m",
        emit_every="1m",
        materialization=MaterializationRule.SKIP_WARMUP,
    )

    assert_frame_equal(frame, before)


if __name__ == "__main__":
    pytest.main([__file__])
