"""A horizon schedule: forward durations, with an identity no window shares.

A horizon is how far AHEAD a target looks: the ``H`` in a forward return
or a forward excursion. It is a duration, generated by the same
recurrence and the same log-spaced placement as the windows, quantized
to the same grain and bounded the same way, so a horizon of ``2h26m`` and
a window of ``2h26m`` spell alike. What they must never share is an
identity. A window schedule names the scales a frame was BUILT at; a
horizon schedule names the distances a target REACHES to; recording one
where the other was expected would let a target quietly inherit the
frame's scales, or a frame a target's reach, with the ids agreeing.

This follows the precedent of :mod:`ohlc_toolkit.schedules.lookback`: a
distinct type whose hashed payload records its members under its own key,
here ``"horizons"``, where a window schedule records ``"windows"`` and a
lookback ``"periods"``. The alternative -- one type with a role marker in
the payload -- was not taken, because a marker is a field a caller can
leave at its default, and the whole point is that a horizon cannot be
mistaken for a window by omission. A distinct key makes each reader
refuse the others' payloads for a missing key, before any value is
looked at.

Unlike the lookback, the values here ARE durations, so the parameter
types are the window generators' own (:class:`MetallicRecurrenceSpec`,
:class:`LogSpacedSpec`, :class:`ExplicitSpec`) and the arithmetic --
quantization, bounding, the recurrence, the log-spaced placement -- is
the shared machinery those generators are themselves built from. A
horizon schedule therefore refuses under exactly the same conditions a
window schedule would, but names itself when it does: a
:class:`~ohlc_toolkit.schedules.generators.ScheduleUnits` states
``"horizon"`` where the window path's own would state ``"window"``,
the same way :data:`~ohlc_toolkit.schedules.lookback.PERIOD_UNITS`
states ``"lookback"`` for a period count.

A horizon schedule carries no emit cadence. The frame a target is
computed on supplies the cadence, and the target primitives refuse a
horizon that is not a whole multiple of it.
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Self

from ohlc_toolkit.config.logging import get_logger
from ohlc_toolkit.schedules.generators import (
    ExplicitSpec,
    GeneratorKind,
    GeneratorSpec,
    LogSpacedSpec,
    MetallicRecurrenceSpec,
    RoundingRule,
    ScheduleUnits,
    _log_spaced_terms,
    _recurrence_terms,
    _resolve_windows,
    require_endpoints_on_the_grain,
    require_resolved_windows,
    require_seed_above_its_own_floor,
)
from ohlc_toolkit.schedules.identity import (
    content_hash,
    durations_from_payload,
    mapping_from_payload,
    require_keys,
    require_recorded_id,
)
from ohlc_toolkit.temporal import (
    ConfigError,
    Duration,
    validate_cadence,
    validate_horizon_duration,
)
from ohlc_toolkit.temporal.echo import enum_from_payload

logger = get_logger(__name__)

_HORIZON_KEYS = ("kind", "parameters", "horizons", "schedule_id")

#: How a horizon schedule describes itself when it refuses. The render
#: callables are the window path's own: a horizon is a Duration, spelled
#: exactly the way a window is, so only the noun differs.
HORIZON_UNITS = ScheduleUnits(
    noun="horizon",
    render=lambda seconds: f"{Duration(seconds)}",
    render_grain=lambda seconds: f"{Duration(seconds)}",
)

# Which parameter class reads which kind's payload: the window generators'
# own classes, because horizons are durations and these are the duration
# specs. Stated here rather than imported from the generators module so
# that this reader's behaviour is visible in this file.
_SPEC_TYPES: dict[
    GeneratorKind,
    type[MetallicRecurrenceSpec] | type[LogSpacedSpec] | type[ExplicitSpec],
] = {
    GeneratorKind.METALLIC_RECURRENCE: MetallicRecurrenceSpec,
    GeneratorKind.LOG_SPACED: LogSpacedSpec,
    GeneratorKind.EXPLICIT: ExplicitSpec,
}

# Which of a kind's recorded parameters are durations. Read back from a
# payload, each is validated as a horizon before the parameter class
# above sees it, so a zero-length value is refused as the thing it was
# recorded as, not as a "Window duration".
_DURATION_PARAMETERS: dict[GeneratorKind, tuple[str, ...]] = {
    GeneratorKind.METALLIC_RECURRENCE: ("seed", "minimum", "maximum"),
    GeneratorKind.LOG_SPACED: ("minimum", "maximum"),
    GeneratorKind.EXPLICIT: (),
}


def _require_horizon_durations(
    kind: GeneratorKind, parameters: Mapping[str, object]
) -> None:
    """Refuse a zero-length recorded duration in the name of a horizon.

    The parameter classes validate the same values again, as windows. By
    then every duration here has passed as a horizon, so their message is
    never the one a reader sees. Anything that is not a duration at all is
    left for the parameter class to refuse by type, as it always has.
    """
    for key in _DURATION_PARAMETERS[kind]:
        value = parameters.get(key)
        if isinstance(value, Duration | str):
            validate_horizon_duration(value)


@dataclass(frozen=True)
class HorizonSchedule:
    """A resolved horizon schedule: its parameters and its horizons.

    Frozen and hashable like its siblings. It has exactly two fields, and
    neither is a cadence: a horizon schedule does not know, and must not
    be told, how often the frame it will be applied to emits.

    Attributes:
        spec: The generator parameters that produced ``horizons``.
        horizons: The fully resolved durations, in generated order. Never
            empty, never repeating, and never longer than
            :data:`~ohlc_toolkit.schedules.generators.MAX_RESOLVED_WINDOWS`.

    """

    spec: GeneratorSpec
    horizons: tuple[Duration, ...]

    def __post_init__(self) -> None:
        """Check the resolved list against the invariants every kind shares.

        The invariants are the window schedule's, because the values are
        the same kind of thing; the refusals therefore name "horizon"
        rather than "window".

        Raises:
            ConfigError: If ``horizons`` is empty, holds anything but a
                strictly positive Duration, holds a repeat, or is longer
                than the cap.

        """
        require_resolved_windows(self.horizons, units=HORIZON_UNITS)

    @property
    def schedule_id(self) -> str:
        """The content hash naming this horizon schedule.

        The payload records its members under ``"horizons"``, where a
        window schedule records ``"windows"`` and a lookback ``"periods"``.
        Two schedules resolved from identical parameters, one as windows
        and one as horizons, therefore never share an id, and each
        reader refuses the other's payload for a missing key.
        """
        return content_hash(self._identity_payload())

    def _identity_payload(self) -> dict[str, object]:
        """Build the payload the schedule id is the hash of."""
        return {
            "kind": self.spec.kind.value,
            "parameters": self.spec.to_dict(),
            "horizons": [str(horizon) for horizon in self.horizons],
        }

    def to_dict(self) -> dict[str, object]:
        """Serialize this schedule to a deterministic, JSON-compatible dict.

        Returns:
            A dict with exactly the keys ``"kind"``, ``"parameters"``,
            ``"horizons"`` and ``"schedule_id"``, in that fixed key order.

        """
        payload = self._identity_payload()
        return {**payload, "schedule_id": content_hash(payload)}

    @classmethod
    def from_dict(cls, data: Mapping[str, object]) -> Self:
        """Reconstruct a horizon schedule from its :meth:`to_dict` form.

        The resolved horizons are read from the payload rather than
        regenerated, for the reason
        :meth:`~ohlc_toolkit.schedules.generators.WindowSchedule.from_dict`
        gives: the recorded list is what the schedule actually used.

        Args:
            data: A mapping as produced by :meth:`to_dict`.

        Returns:
            The reconstructed schedule.

        Raises:
            ConfigError: If a key is missing -- which is what a window or
                lookback schedule's payload looks like here, since neither
                records ``"horizons"`` -- the kind names no generator, any
                parameter or horizon is malformed, the list breaks an
                invariant, or the recorded id does not match the payload
                it names.

        """
        require_keys(data, _HORIZON_KEYS, label="horizon schedule")
        kind = enum_from_payload(GeneratorKind, data["kind"], label="generator kind")
        parameters = mapping_from_payload(
            data["parameters"], label="horizon schedule parameters"
        )
        _require_horizon_durations(kind, parameters)
        schedule = cls(
            spec=_SPEC_TYPES[kind].from_dict(parameters),
            horizons=durations_from_payload(data["horizons"], label="horizon"),
        )
        require_recorded_id(
            data["schedule_id"], schedule.schedule_id, label="schedule_id"
        )
        return schedule


def metallic_horizons(  # noqa: PLR0913 - one keyword per recorded parameter
    *,
    coefficient: float,
    seed: Duration | str,
    grain: Duration | str,
    maximum: Duration | str,
    minimum: Duration | str | None = None,
    rounding: RoundingRule = RoundingRule.NEAREST_TIES_AWAY,
) -> HorizonSchedule:
    """Resolve a horizon schedule from a two-term linear recurrence.

    The same arithmetic and bounds as
    :func:`~ohlc_toolkit.schedules.generators.metallic_recurrence`, and a
    refusal under exactly the same conditions; only the identity, and the
    noun a refusal names, differ. See that function for the parameters.

    Returns:
        The resolved horizon schedule.

    Raises:
        ConfigError: Exactly when the window generator would refuse the
            same parameters.

    """
    spec = MetallicRecurrenceSpec(
        coefficient=coefficient,
        seed=validate_horizon_duration(seed),
        grain=validate_cadence(grain),
        maximum=validate_horizon_duration(maximum),
        minimum=None if minimum is None else validate_horizon_duration(minimum),
        rounding=rounding,
    )
    require_seed_above_its_own_floor(
        seed=spec.seed.total_seconds,
        minimum=None if spec.minimum is None else spec.minimum.total_seconds,
        grain=spec.grain.total_seconds,
        rounding=spec.rounding,
        units=HORIZON_UNITS,
    )
    horizons = _resolve_windows(
        _recurrence_terms(spec, units=HORIZON_UNITS),
        grain=spec.grain,
        rounding=spec.rounding,
        minimum=spec.minimum,
        maximum=spec.maximum,
        units=HORIZON_UNITS,
    )
    logger.debug(
        "Resolved a metallic horizon schedule of {} horizon(s) from a {} seed.",
        len(horizons),
        spec.seed,
    )
    return HorizonSchedule(spec=spec, horizons=horizons)


def log_spaced_horizons(
    *,
    count: int,
    minimum: Duration | str,
    maximum: Duration | str,
    grain: Duration | str,
    rounding: RoundingRule = RoundingRule.NEAREST_TIES_AWAY,
) -> HorizonSchedule:
    """Resolve a horizon schedule of log-spaced durations between two bounds.

    The same placement and bounds as
    :func:`~ohlc_toolkit.schedules.generators.log_spaced`, and a refusal
    under exactly the same conditions; only the identity, and the noun a
    refusal names, differ. See that function for the parameters.

    Returns:
        The resolved horizon schedule.

    Raises:
        ConfigError: Exactly when the window generator would refuse the
            same parameters.

    """
    spec = LogSpacedSpec(
        count=count,
        minimum=validate_horizon_duration(minimum),
        maximum=validate_horizon_duration(maximum),
        grain=validate_cadence(grain),
        rounding=rounding,
    )
    require_endpoints_on_the_grain(
        minimum=spec.minimum.total_seconds,
        maximum=spec.maximum.total_seconds,
        grain=spec.grain.total_seconds,
        rounding=spec.rounding,
        units=HORIZON_UNITS,
    )
    horizons = _resolve_windows(
        _log_spaced_terms(spec),
        grain=spec.grain,
        rounding=spec.rounding,
        minimum=spec.minimum,
        maximum=spec.maximum,
        units=HORIZON_UNITS,
    )
    logger.debug(
        "Resolved a log-spaced horizon schedule of {} horizon(s) from {} point(s).",
        len(horizons),
        spec.count,
    )
    return HorizonSchedule(spec=spec, horizons=horizons)


def explicit_horizons(
    horizons: Sequence[Duration | str], *, name: str | None = None
) -> HorizonSchedule:
    """State a horizon schedule rather than generating one.

    Args:
        horizons: The durations, as Durations or compact duration strings,
            in the order they should be recorded.
        name: The name a registered list is asked for by. Defaults to
            None, for an ad-hoc list.

    Returns:
        The horizon schedule, carrying the given durations and the name.

    Raises:
        ConfigError: Exactly when
            :func:`~ohlc_toolkit.schedules.generators.explicit` would
            refuse the same list.

    """
    if isinstance(horizons, str) or not isinstance(horizons, Sequence):
        logger.warning(
            "Rejecting an explicit schedule that is not a list: {}",
            type(horizons).__name__,
        )
        raise ConfigError(
            f"An explicit schedule takes a list of durations, got "
            f"{type(horizons).__name__}"
        )
    resolved = tuple(validate_horizon_duration(horizon) for horizon in horizons)
    logger.debug("Recorded an explicit schedule of {} horizon(s).", len(resolved))
    return HorizonSchedule(spec=ExplicitSpec(name=name), horizons=resolved)
