"""A horizon schedule: forward durations, with an identity no window shares.

A horizon is how far AHEAD a target looks: the ``H`` in a forward return
or a forward excursion. It is a duration, generated by the same
recurrence and the same log-spaced placement as the windows, quantized
to the same grain and bounded the same way, so a horizon of ``2h26m`` and
a window of ``2h26m`` spell alike. What they must never share is an
identity. A window schedule names the scales a frame was BUILT at; a
horizon schedule names the distances a target REACHES to; recording one
where the other was expected would let a target quietly inherit the
frame's scales, or a frame a target's reach, with the ids agreeing.

This follows the precedent of :mod:`ohlc_toolkit.schedules.lookback`: a
distinct type whose hashed payload records its members under its own key,
here ``"horizons"``, where a window schedule records ``"windows"`` and a
lookback ``"periods"``. The alternative -- one type with a role marker in
the payload -- was not taken, because a marker is a field a caller can
leave at its default, and the whole point is that a horizon cannot be
mistaken for a window by omission. A distinct key makes each reader
refuse the others' payloads for a missing key, before any value is
looked at.

Unlike the lookback, the values here ARE durations, so the parameter
types are the window generators' own (:class:`MetallicRecurrenceSpec`,
:class:`LogSpacedSpec`, :class:`ExplicitSpec`) and resolution goes
through the window generators themselves. A horizon schedule therefore
has exactly the bound refusals a window schedule has, in the words those
refusals already use.

A horizon schedule carries no emit cadence. The frame a target is
computed on supplies the cadence, and the target primitives refuse a
horizon that is not a whole multiple of it.
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Self

from ohlc_toolkit.config.logging import get_logger
from ohlc_toolkit.schedules.generators import (
    ExplicitSpec,
    GeneratorKind,
    GeneratorSpec,
    LogSpacedSpec,
    MetallicRecurrenceSpec,
    RoundingRule,
    WindowSchedule,
    explicit,
    log_spaced,
    metallic_recurrence,
    require_resolved_windows,
)
from ohlc_toolkit.schedules.identity import (
    content_hash,
    durations_from_payload,
    mapping_from_payload,
    require_keys,
    require_recorded_id,
)
from ohlc_toolkit.temporal import Duration
from ohlc_toolkit.temporal.echo import enum_from_payload

logger = get_logger(__name__)

_HORIZON_KEYS = ("kind", "parameters", "horizons", "schedule_id")

# Which parameter class reads which kind's payload: the window generators'
# own classes, because horizons are durations and these are the duration
# specs. Stated here rather than imported from the generators module so
# that this reader's behaviour is visible in this file.
_SPEC_TYPES: dict[
    GeneratorKind,
    type[MetallicRecurrenceSpec] | type[LogSpacedSpec] | type[ExplicitSpec],
] = {
    GeneratorKind.METALLIC_RECURRENCE: MetallicRecurrenceSpec,
    GeneratorKind.LOG_SPACED: LogSpacedSpec,
    GeneratorKind.EXPLICIT: ExplicitSpec,
}


@dataclass(frozen=True)
class HorizonSchedule:
    """A resolved horizon schedule: its parameters and its horizons.

    Frozen and hashable like its siblings. It has exactly two fields, and
    neither is a cadence: a horizon schedule does not know, and must not
    be told, how often the frame it will be applied to emits.

    Attributes:
        spec: The generator parameters that produced ``horizons``.
        horizons: The fully resolved durations, in generated order. Never
            empty, never repeating, and never longer than
            :data:`~ohlc_toolkit.schedules.generators.MAX_RESOLVED_WINDOWS`.

    """

    spec: GeneratorSpec
    horizons: tuple[Duration, ...]

    def __post_init__(self) -> None:
        """Check the resolved list against the invariants every kind shares.

        The invariants are the window schedule's, because the values are
        the same kind of thing; the refusals therefore say "window".

        Raises:
            ConfigError: If ``horizons`` is empty, holds anything but a
                strictly positive Duration, holds a repeat, or is longer
                than the cap.

        """
        require_resolved_windows(self.horizons)

    @property
    def schedule_id(self) -> str:
        """The content hash naming this horizon schedule.

        The payload records its members under ``"horizons"``, where a
        window schedule records ``"windows"`` and a lookback ``"periods"``.
        Two schedules resolved from identical parameters, one as windows
        and one as horizons, therefore never share an id, and each
        reader refuses the other's payload for a missing key.
        """
        return content_hash(self._identity_payload())

    def _identity_payload(self) -> dict[str, object]:
        """Build the payload the schedule id is the hash of."""
        return {
            "kind": self.spec.kind.value,
            "parameters": self.spec.to_dict(),
            "horizons": [str(horizon) for horizon in self.horizons],
        }

    def to_dict(self) -> dict[str, object]:
        """Serialize this schedule to a deterministic, JSON-compatible dict.

        Returns:
            A dict with exactly the keys ``"kind"``, ``"parameters"``,
            ``"horizons"`` and ``"schedule_id"``, in that fixed key order.

        """
        payload = self._identity_payload()
        return {**payload, "schedule_id": content_hash(payload)}

    @classmethod
    def from_dict(cls, data: Mapping[str, object]) -> Self:
        """Reconstruct a horizon schedule from its :meth:`to_dict` form.

        The resolved horizons are read from the payload rather than
        regenerated, for the reason
        :meth:`~ohlc_toolkit.schedules.generators.WindowSchedule.from_dict`
        gives: the recorded list is what the schedule actually used.

        Args:
            data: A mapping as produced by :meth:`to_dict`.

        Returns:
            The reconstructed schedule.

        Raises:
            ConfigError: If a key is missing -- which is what a window or
                lookback schedule's payload looks like here, since neither
                records ``"horizons"`` -- the kind names no generator, any
                parameter or horizon is malformed, the list breaks an
                invariant, or the recorded id does not match the payload
                it names.

        """
        require_keys(data, _HORIZON_KEYS, label="horizon schedule")
        kind = enum_from_payload(GeneratorKind, data["kind"], label="generator kind")
        parameters = mapping_from_payload(
            data["parameters"], label="horizon schedule parameters"
        )
        schedule = cls(
            spec=_SPEC_TYPES[kind].from_dict(parameters),
            horizons=durations_from_payload(data["horizons"], label="horizon"),
        )
        require_recorded_id(
            data["schedule_id"], schedule.schedule_id, label="schedule_id"
        )
        return schedule


def _as_horizons(schedule: WindowSchedule) -> HorizonSchedule:
    """Re-record a resolved window schedule's durations as horizons.

    The one place the two types meet, and it runs in one direction only:
    the generator did its work as a window schedule, and this takes the
    parameters and the resolved list and records them under the horizon
    identity. Nothing about the values changes; what changes is what they
    are a schedule OF.
    """
    logger.debug(
        "Recorded {} horizon(s) from a {} generator.",
        len(schedule.windows),
        schedule.spec.kind.value,
    )
    return HorizonSchedule(spec=schedule.spec, horizons=schedule.windows)


def metallic_horizons(  # noqa: PLR0913 - one keyword per recorded parameter
    *,
    coefficient: float,
    seed: Duration | str,
    grain: Duration | str,
    maximum: Duration | str,
    minimum: Duration | str | None = None,
    rounding: RoundingRule = RoundingRule.NEAREST_TIES_AWAY,
) -> HorizonSchedule:
    """Resolve a horizon schedule from a two-term linear recurrence.

    The same arithmetic, bounds and refusals as
    :func:`~ohlc_toolkit.schedules.generators.metallic_recurrence`; only
    the identity differs. See that function for the parameters.

    Returns:
        The resolved horizon schedule.

    Raises:
        ConfigError: Exactly when the window generator would refuse the
            same parameters.

    """
    return _as_horizons(
        metallic_recurrence(
            coefficient=coefficient,
            seed=seed,
            grain=grain,
            maximum=maximum,
            minimum=minimum,
            rounding=rounding,
        )
    )


def log_spaced_horizons(
    *,
    count: int,
    minimum: Duration | str,
    maximum: Duration | str,
    grain: Duration | str,
    rounding: RoundingRule = RoundingRule.NEAREST_TIES_AWAY,
) -> HorizonSchedule:
    """Resolve a horizon schedule of log-spaced durations between two bounds.

    The same placement, bounds and refusals as
    :func:`~ohlc_toolkit.schedules.generators.log_spaced`; only the
    identity differs. See that function for the parameters.

    Returns:
        The resolved horizon schedule.

    Raises:
        ConfigError: Exactly when the window generator would refuse the
            same parameters.

    """
    return _as_horizons(
        log_spaced(
            count=count,
            minimum=minimum,
            maximum=maximum,
            grain=grain,
            rounding=rounding,
        )
    )


def explicit_horizons(
    horizons: Sequence[Duration | str], *, name: str | None = None
) -> HorizonSchedule:
    """State a horizon schedule rather than generating one.

    Args:
        horizons: The durations, as Durations or compact duration strings,
            in the order they should be recorded.
        name: The name a registered list is asked for by. Defaults to
            None, for an ad-hoc list.

    Returns:
        The horizon schedule, carrying the given durations and the name.

    Raises:
        ConfigError: Exactly when
            :func:`~ohlc_toolkit.schedules.generators.explicit` would
            refuse the same list.

    """
    return _as_horizons(explicit(horizons, name=name))
