"""Named window schedules, as data a caller asks for by name.

Nothing here is a default. Nothing in this package consults this
registry on its own: a schedule reaches a caller only because that
caller named it. The registry exists so that a list worth reproducing
exactly -- a control, or the output of an implementation that no longer
exists -- can be recorded, compared, and hashed like any other
schedule, instead of being retyped from memory at each use site.

Each registration is an explicit schedule: a resolved list under a name,
generated by nothing. That is deliberate. A registration whose values
were recomputed by a generator at import time would change the day the
generator changed, which is the opposite of what a registration is for.
"""

from ohlc_toolkit.config.logging import get_logger
from ohlc_toolkit.schedules.generators import WindowSchedule, explicit
from ohlc_toolkit.temporal import ConfigError, bounded_echo

logger = get_logger(__name__)

# The window scales, in minutes, that an earlier implementation of the
# metallic recurrence produced: it truncated every term to whole minutes
# BEFORE feeding it back into the recurrence, so its rounding error was
# multiplied by the coefficient at every step and compounded. Kept
# verbatim so a result computed against it can be reproduced and
# compared. It is not what
# :func:`~ohlc_toolkit.schedules.metallic_recurrence` produces from the
# same parameters, and is not meant to be.
_METALLIC_LEGACY_2025_MINUTES = (
    1,
    3,
    7,
    18,
    47,
    122,
    318,
    829,
    2163,
    5643,
    14723,
)

METALLIC_LEGACY_2025 = "metallic-legacy-2025"

_NAMED_SCHEDULES: dict[str, WindowSchedule] = {
    METALLIC_LEGACY_2025: explicit(
        [f"{minutes}m" for minutes in _METALLIC_LEGACY_2025_MINUTES],
        name=METALLIC_LEGACY_2025,
    ),
}


def named_schedule_names() -> tuple[str, ...]:
    """List every registered schedule name, in registration order.

    Returns:
        The names :func:`named_schedule` will resolve.

    """
    return tuple(_NAMED_SCHEDULES)


def named_schedule(name: str) -> WindowSchedule:
    """Look up a registered schedule by name.

    Args:
        name: The registered name, exactly as
            :func:`named_schedule_names` reports it.

    Returns:
        The registered schedule. Schedules are frozen values, so the
        same instance is handed to every caller.

    Raises:
        ConfigError: If ``name`` is not a string, or names no
            registration. There is no fallback: a typo that quietly
            resolved to some other schedule would be a silently
            different experiment.

    """
    if not isinstance(name, str):
        logger.warning("Rejecting a non-string schedule name: {!r}", name)
        raise ConfigError(f"A schedule name must be a str, got {type(name).__name__}")

    schedule = _NAMED_SCHEDULES.get(name)
    if schedule is None:
        quoted = bounded_echo(name)
        logger.warning("Rejecting an unknown schedule name: {}", quoted)
        raise ConfigError(
            f"Unknown schedule name {quoted}. Registered: "
            f"{list(named_schedule_names())}."
        )
    return schedule
